//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custom_Crosshairs {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class UserPreferances : global::System.Configuration.ApplicationSettingsBase {
        
        private static UserPreferances defaultInstance = ((UserPreferances)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UserPreferances())));
        
        public static UserPreferances Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/data/images/Advanced/Crosshair_Drop_Large.png")]
        public string userImagePath {
            get {
                return ((string)(this["userImagePath"]));
            }
            set {
                this["userImagePath"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/data/images/Simple/Basic_Crosshair.png")]
        public string defaultImagePath {
            get {
                return ((string)(this["defaultImagePath"]));
            }
        }
    }
}
