//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custom_Crosshairs {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class UserPreferances : global::System.Configuration.ApplicationSettingsBase {
        
        private static UserPreferances defaultInstance = ((UserPreferances)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UserPreferances())));
        
        public static UserPreferances Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Simple_Crosshair.png")]
        public string preferedCrosshair {
            get {
                return ((string)(this["preferedCrosshair"]));
            }
            set {
                this["preferedCrosshair"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Simple_Crosshair.png")]
        public string defaultCrosshair {
            get {
                return ((string)(this["defaultCrosshair"]));
            }
            set {
                this["defaultCrosshair"] = value;
            }
        }
    }
}
